### PR TITLE
Include working NavLink component within Layout

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouter.com/en/6.14.2/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by hajschroeder**
## Description

This PR includes the NavLink component provided by React Router. Instead of using <a> tags within the layout, this update uses the NavLink component to allow users to click through the current available pages of the application.

## Related Issue
closes #2 

## Acceptance Criteria

 - The nav element is added to the Layout component
 - Links to the "Home", "List", and "Add item" pages of the app are In the nav element
 - The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with `git pull origin as-ds-navigation` and check that branch out with `git checkout as-ds-navigation`
- Run `npm start` to launch the app
- Click through the navigation links to make sure they navigate to their respective pages.

### CODE REVIEW

**Review by codecaviette — APPROVED** [review]
Links are working beautifully by navigating to correct pages using the NavLink component.

**Review by thetrend — APPROVED** [review]
Great job using ternary operators! 🎉

**Comment by MagdaSlifierz** [comment]
Links are working as expected. I can navigate to the correct pages.

**Review by MagdaSlifierz — APPROVED** [review]
Links are working as expected. I can navigate to the correct pages.

**Pull request merged**
