### PR TITLE
Hs ms new shopping list

### PR DESCRIPTION
**Pull request by MagdaSlifierz**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
The user wants to create a new shopping list to keep track of things they buy. To do this, they need to make a new token.

## Acceptance Criteria

- [ ] @the-collab-lab/shopping-list-utils is added as a dependency to the project.
- [ ] The string my test list in App.jsx is replaced with null, so users are not automatically subscribed to any list.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

- Integrated the dependency @the-collab-lab/shopping-list-utils into the project.
- Replaced the occurrence of the string "my test list" in the file App.jsx with null, ensuring users are not automatically subscribed to any particular list.
- If a user lacks a token:
- Redirected them from the List (/list) page to the homepage (/).
- Provided a button within the Home component that enables users to establish a new list.
- Upon clicking this button, employed the setListToken function in App.jsx to generate and store a new token in the localStorage.
- After successful token creation and storage, redirect the user to the List view.
- For users possessing a token:
- Implemented automatic redirection to the List (/list) page.

### After

https://github.com/the-collab-lab/tcl-62-smart-shopping-list/assets/49603115/1ff5405b-552a-4087-ab5c-152bc85beb68

## Testing Steps / QA Criteria

Steps:
1. From your terminal, pull down the branch with git pull origin hs-ms-new-shopping-list and check that branch out with git checkout hs-ms-new-shopping-list
2. Install Dependencies.  Run `npm install` to install new packages that have been added to the project.
3. Run `npm start` to start the development server. This will open the app in your default web browser.
4. Navigate to the homepage and locate the "Create a new list" button. Upon clicking the button, the system should check if a token has been generated. If a token exists, the user will be redirected to the list page. However, if the token is deleted and the user attempts to access the list page, they will be redirected back to the homepage.
5. Testing Local Storage Behavior - Token Deletion:
   - Perform the following steps to test the behavior related to local storage:
     1: Create a new list using the button and navigate to the list view.
     2: Open your browser's developer tools.
     3: Go to the "Application" tab in the developer tools and locate "Local Storage."
     4: Delete the relevant token 
     5: Refresh the browser.
     6: Verify that the list view redirects to the home page, as expected.
6.  Additional Browser Testing:
    - If necessary, open the app in a different browser (if you were using Chrome for development, try Firefox or Edge).
    - Clear local storage for the new browser.
    - Repeat the testing steps to ensure consistent behavior across different browsers.

### CODE REVIEW

**Review by avinashi10 — COMMENTED** [review]
The button renders successfully and upon clicking navigates to a new list. When I delete the key from my local storage and refresh the browser, the list view redirects the the home page. Manually clicking 'list' from the navigation also redirects home. I'd recommend updating your PR testing instructions with more details. Let testers know they'll need to run npm install as you've added a package, and let them know they'll need to run the app in a different browser than what they were developing in, or clear local storage. Also tell them how to test for all the things you describe (e.g. once you successfully create a new list, go to your local storage and delete the token). I had to do a lot of guessing and checking as well as troubleshooting to test these features - clearer testing instructions would be helpful!

**Comment by codecaviette** [comment]
Agree with @avinashi10 's comments. Otherwise, LGTM!

**Review by codecaviette — APPROVED** [review]

**Review by codecaviette — APPROVED** [review]
Thanks for adding more detailed instructions for testing purposes. LGTM!

**Comment by lyleschemmerling** [comment]
I couldn't figure out how to break this and the code looks good. LGTM

**Review by avinashi10 — APPROVED** [review]

**Review by lyleschemmerling — APPROVED** [review]

**Pull request merged**
